Lo siguiente está basado en el libro de Álgebra Lineal de Grossman, S. y Flores, J.

# Vectores

## Vector renglón de $n$ componentes 

Un vector de $n$ componentes se define como un conjunto **ordenado** de $n$ números escritos de la siguiente forma: $(x_1, x_2, \dots, x_n)$

## Vector columna  de $n$ componentes 

Un vector columna de $n$ componentes es un conjunto **ordenado** de $n$ números escritos de la siguiente forma: 
$\left( 
\begin{array}{c}
x_1\\
x_2\\
\vdots\\
x_n
\end{array}
\right)$

**Obs:** $x_k$ se denomina la **k-ésima** componente del vector y puede estar en algún conjunto de números como $\mathbb{R}$ o $\mathbb{C}$. Típicamente si no se especifica el conjunto se supone $\mathbb{R}$.

Los vectores renglón se encuentran en el conjunto $\mathbb{R}^{1xn}$ y los vectores columna se encuentran en el conjunto $\mathbb{R}^{nx1}$ o simplemente $\mathbb{R}^n$.

### En numpy...

**En numpy creamos array's de la siguiente forma: (un array en numpy se considera tanto columna o vector y dependiendo del uso se toma uno u otro)**

In [2]:
import numpy as np
import pprint
v = np.array([1,2,3])
pprint.pprint(v)

array([1, 2, 3])


**y cada array tiene atributos `ndim` (número de dimensiones), `shape` (tamaño de cada dimensión) y `size` (el tamaño total del array) y `dtype` el tipo de dato del array**

In [5]:
print('v.ndim:', v.ndim)
print('v.shape:', v.shape)
print('v.size:', v.size)
print('v.dtype', v.dtype)

v.ndim: 1
v.shape: (3,)
v.size: 3
v.dtype int64


**accedemos con corchetes a sus componentes**

In [20]:
print('primer elemento', v[0])
print('último elemento', v[-1])
print('segundo elemento', v[1])
print('penúltimo elemento', v[-2])
print('del primero al 2º elemento incluyendo este último', v[:2])
print('del 2º al último elemento sin incluir el 2º', v[2:])

primer elemento 1
último elemento 3
segundo elemento 2
penúltimo elemento 2
del primero al 2º elemento incluyendo este último [1 2]
del 2º al último elemento sin incluir el 2º [3]


**otra forma de generar arrays en numpy es con la función arange o random para un array pseudo aleatorio:**

In [10]:
pprint.pprint(np.arange(5))
pprint.pprint(np.arange(0,1,.2))

array([0, 1, 2, 3, 4])
array([0. , 0.2, 0.4, 0.6, 0.8])


In [24]:
#array pseudo aleatorio
np.random.seed(1989)
pprint.pprint(np.random.randint(5, size=3)) #números enteros pseudo aleatorios del 0 al 4

array([2, 4, 4])


ver: 
* [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
* [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html)
* [numpy-for-matlab-users](https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html)

**Para obtener vectores renglón se puede utilizar la función `reshape`**

In [22]:
v.reshape(1,3)

array([[1, 2, 3]])

**y vectores columna con:**

In [23]:
v.reshape(3,1)

array([[1],
       [2],
       [3]])

ver: [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

# Matrices

El arreglo de coeficientes: $$\begin{bmatrix} a_{11} & a_{12} & \cdots& a_{1n} \\ a_{21} & a_{22} & \cdots& a_{2n} \\ &&\vdots \\ a_{m1} & a_{m2} & \cdots& a_{mn} \end{bmatrix}$$ 

se le llama matriz de coeficientes del sistema y la matriz de coeficientes aumentada con el lado derecho se le llama matriz aumentada: $$ \left [\begin{array}{cccc|c} a_{11} & a_{12} & \cdots& a_{1n} & b_1 \\ a_{21} & a_{22} & \cdots& a_{2n} & b_2 \\ && \vdots& & \\ a_{m1} & a_{m2} & \cdots& a_{mn} & b_m \end{array} \right ]$$

Si a la matriz de coeficientes se denota por $A$ y el lado derecho por $b$ entonces la matriz aumentada es $[A|b]$.

**Def** Formalmente un escalar es un número real o complejo y una matriz es un arreglo rectangular de escalares y se escribe $A \in \mathbb{R}^{mxn}$ o $A \in \mathbb{C}^{mxn}$ para denotar que $A$ es un arreglo de dos dimensiones de números reales o de números complejos respectivamente y $A$ tiene dimensiones $mxn$: $m$ renglones y $n$ columnas.

Una matriz se nombra cuadrada si $m=n$ y rectangular si $m \neq n$.

**Def** Una submatriz de una matriz $A$ es un arreglo que se forma al eliminar cualquier combinación de renglones y columnas de $A$. Por ejemplo, $B = \begin{bmatrix} 2 &4 \\ -3& 7\end{bmatrix}$ es una submatriz de $A = \begin{bmatrix} 2 &1& 3& 4 \\ 8& 6& 5& -9\\ -3& 8& 3& 7 \end{bmatrix}$.

El símbolo $A_{i*}$ es utilizado para denotar el $i$-ésimo renglón de $A$ y $A_{*j}$ la $j$-ésima columna de A. Por ejemplo $A_{2*} = \begin{bmatrix} 8& 6& 5& -9 \end{bmatrix}$ y $A_{*2} = \begin{bmatrix} 1 \\6\\8 \end{bmatrix}$ en la definición anterior.

### En numpy...

**En numpy creamos arrays de dos dimensiones de la siguiente forma:**

In [1]:
import numpy as np
import pprint
A = np.array([[1,2,3],[4,5,6]])
pprint.pprint(A)

array([[1, 2, 3],
       [4, 5, 6]])


**y cada array tiene atributos `ndim` (número de dimensiones), `shape` (tamaño de cada dimensión) y `size` (el tamaño total del array) y `dtype` el tipo de dato del array**

In [2]:
print('A.ndim:', A.ndim)
print('A.shape:', A.shape)
print('A.size:', A.size)
print('A.dtype', A.dtype)

A.ndim: 2
A.shape: (2, 3)
A.size: 6
A.dtype int64


**accedemos con corchetes a sus componentes**

In [3]:
print('elemento en la posición (0,0):', A[0][0])
print('elemento en la posición (1,2):', A[1][2])
#también con la siguiente notación:
print('elemento en la posición (0,0):', A[0,0])
print('elemento en la posición (1,2):', A[1,2])

elemento en la posición (0,0): 1
elemento en la posición (1,2): 6
elemento en la posición (0,0): 1
elemento en la posición (1,2): 6


In [4]:
print('primer columna:', A[:,0])
print('tercer columna:', A[:,2])
print('segundo renglón:', A[1,:])

primer columna: [1 4]
tercer columna: [3 6]
segundo renglón: [4 5 6]


**otra forma de generar arrays en numpy es con la función arange o random para un array pseudo aleatorio:**

In [5]:
pprint.pprint(np.arange(6).reshape(2,3))
pprint.pprint(np.arange(0,1.2,.2).reshape(3,2))

array([[0, 1, 2],
       [3, 4, 5]])
array([[0. , 0.2],
       [0.4, 0.6],
       [0.8, 1. ]])


In [6]:
#array pseudo aleatorio
np.random.seed(1989)
pprint.pprint(np.random.randint(5, size=(3,2))) #números enteros pseudo aleatorios del 0 al 4

array([[2, 4],
       [4, 2],
       [3, 4]])


ver: 
* [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)
* [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html)